version: "3"

services:
    mysql-camunda:
        image: mysql:latest
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: camunda
            MYSQL_ROOT_PASSWORD: changeme
            
volumes:
    mysql-data: