camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    database:
      schema-update: drop-create
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camunda
    username: root
    password: changeme
    driver-class-name: com.mysql.cj.jdbc.Driver

